-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 01, 2022 at 11:39 AM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 8.0.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ecommerce`
--

-- --------------------------------------------------------

--
-- Table structure for table `productdb`
--

CREATE TABLE `productdb` (
  `Prod_id` int(128) NOT NULL,
  `image_loc` varchar(255) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `launch_d` date DEFAULT NULL,
  `description` varchar(255) NOT NULL,
  `specification` text DEFAULT NULL,
  `price` int(128) NOT NULL,
  `hits` int(128) NOT NULL,
  `buy_count` int(128) NOT NULL,
  `category` varchar(255) DEFAULT NULL,
  `Tags` varchar(256) DEFAULT NULL,
  `mrp_price` int(128) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `productdb`
--

INSERT INTO `productdb` (`Prod_id`, `image_loc`, `title`, `launch_d`, `description`, `specification`, `price`, `hits`, `buy_count`, `category`, `Tags`, `mrp_price`) VALUES
(1, 'assets/images/Upload/Mobiles/1.png&assets/images/Upload/Mobiles/2.png&assets/images/Upload/Mobiles/3.png&assets/images/Upload/Mobiles/4.png&assets/images/Upload/Mobiles/5.png', 'SAMSUNG Galaxy S20+ (Cosmic Black, 128 GB)  (8 GB RAM)', '2022-05-21', 'Say hello to the powerful and stylish Samsung Galaxy S20+ smartphone. Featuring a 64 MP high-resolution camera with 30X Zoom, you can capture stunning photos like never before on this smartphone. It also comes with a long-lasting 4500 mAh battery so you c', '[\n  [\"RAM\",\"‎8 GB\"  ],\n  [\"Product Dimensions\",\"‎0.84 x 7.45 x 15.98 cm; 190 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Ion batteries required. (included)\"  ],\n  [\"Item model number\",\"‎SM-G781BZBGINS\"  ],\n  [\"Connectivity technologies\",\"‎WiFi 5G; WLAN; Bluetooth; GPS; NFC; Radio; USB\"  ],\n  [\"Special features\",\"‎Rear Camera, Dual_Sim, Camera, Fast Charging, Hybrid Sim Slot\"  ],\n  [\"Display technology\",\"‎AMOLED\"  ],\n  [\"Colours displayed\",\"‎Infinity-O Super Display with 120Hz Refresh rate\"  ],\n  [\"Other display features\",\"‎Wireless\"  ],\n  [\"Device Interface - primary\",\"‎Touchscreen\"  ],\n  [\"Other camera features\",\"‎Triple Rear Camera (12 MP + 8 MP + 12 MP) | 32 MP Front Camera\"  ],\n  [\"Form factor\",\"‎Bar\"  ],\n  [\"Colour\",\"‎Cloud Navy\"  ],\n  [\"Battery Power Rating\",\"‎4500\"  ],\n  [\"Whats in the box\",\"‎Handset, Non-removable Battery Included, Travel Adapter, USB Cable, User Manual\"  ],\n  [\"Manufacturer\",\"‎Samsung\"  ],\n  [\"Country of Origin\",\"‎India\"  ],\n  [\"Item Weight\",\"‎190 g\"  ]\n]', 54999, 60, 40000, 'phone', 'Smartphone&Android 10&Octa Core&64 GB ROM&4 GB RAM&2.3Hz Clock Speed&512 Expandable storage&5MP front camera&Dual Sim&Royal Blue&HD+&MIUI 12', 60000),
(3, 'assets/images/Upload/Laptop/1.png&assets/images/Upload/Laptop/2.png&assets/images/Upload/Laptop/3.png&assets/images/Upload/Laptop/4.png&assets/images/Upload/Laptop/5.png&assets/images/Upload/Laptop/6.png&assets/images/Upload/Laptop/7.png', 'ASUS ROG Strix G15 Ryzen 9 Octa Core 5900HX', '2022-05-21', '16 GB/512 GB SSD/Windows 10 Home/4 GB Graphics/NVIDIA GeForce RTX 3050 Ti, G513QE-HN166TS Gaming Laptop, 15.6 inch, Eclipse Gray, 2.10 kg.', '[\n  [\"Manufacturer\",\"‎Tech Front iNC.\"  ],\n  [\"Series\",\"‎ASUS ROG Strix G15\"  ],\n  [\"Form Factor\",\"‎Laptop\"  ],\n  [\"Item Height\",\"‎8 Centimeters\"  ],\n  [\"Item Width\",\"‎15 Centimeters\"  ],\n  [\"Standing screen display size\",\"‎15.6 Inches\"  ],\n  [\"Product Dimensions\",\"‎35 x 15 x 8 cm; 2.3 Kilograms\"  ],\n  [\"Processor Brand\",\"‎AMD\"  ],\n  [\"Processor Type\",\"‎Ryzen 9\"  ],\n  [\"Processor Speed\",\"‎3.3 GHz\"  ],\n  [\"Processor Count\",\"‎1\"  ],\n  [\"RAM Size\",\"‎8 GB\"  ],\n  [\"Memory Technology\",\"‎DDR4\"  ],\n  [\"Maximum Memory Supported\",\"‎8 GB\"  ],\n  [\"Hard Drive Size\",\"‎1 TB\"  ],\n  [\"Hard Disk Description\",\"‎SSD\"  ],\n  [\"Graphics Coprocessor\",\"‎NVIDIA GeForce RTX 3060\"  ],\n  [\"Graphics Chipset Brand\",\"‎NVIDIA\"  ],\n  [\"Graphics Card Description\",\"‎Dedicated\"  ],\n  [\"Graphics RAM Type\",\"‎GDDR6\"  ],\n  [\"Graphics Card Ram Size\",\"‎6 GB\"  ],\n  [\"Graphics Card Interface\",\"‎Integrated\"  ],\n  [\"Number of USB 2.0 Ports\",\"‎2\"  ],\n  [\"Number of USB 3.0 Ports\",\"‎1\"  ],\n  [\"Optical Drive Type\",\"‎No\"  ],\n  [\"Operating System\",\"‎Windows 10 Home\"  ],\n  [\"Included Components\",\"‎Laptop, Adaptor, Manual\"  ],\n  [\"Manufacturer\",\"‎Tech Front iNC.\"  ],\n  [\"Country of Origin\",\"‎China\"  ],\n  [\"Item Weight\",\"‎2 kg 300 g\"  ],\n  [\"ASIN\",\"B09SHMF4MD\"  ],\n  [\"Best Sellers Rank\",\"#203,630 in Computers & Accessories (See Top 100 in Computers & Accessories) \\n  #7,725 in Laptops\"  ],\n  [\"Date First Available\",\"15 February 2022\"  ],\n  [\"Item Dimensions LxWxH\",\"35 x 15 x 8 Centimeters\"  ],\n  [\"Net Quantity\",\"1.00 Unit\"  ]\n]', 97990, 60, 40000, 'laptop', NULL, 100000),
(4, 'assets/images/Upload/Headphones/1.png&assets/images/Upload/Headphones/2.png&assets/images/Upload/Headphones/3.png&assets/images/Upload/Headphones/4.png&assets/images/Upload/Headphones/5.png&assets/images/Upload/Headphones/6.png', 'boAt Rockerz 370 Bluetooth Headset', '2022-05-21', 'If you are looking for a wallet-friendly wireless headset then this boAt headset is ideal for you. A complete charging session ensures that you receive a playback time of up to 8 hours. Moreover, it allows wired and wireless connectivity with AUX and Blue', '[\n  [\"Manufacturer\",\"‎Imagine Marketing Ltd, info@imaginemarketingindia.com\"  ],\n  [\"Model\",\"‎Rockerz 370\"  ],\n  [\"Model Name\",\"‎Rockerz 370\"  ],\n  [\"Product Dimensions\",\"‎7 x 18 x 16 cm; 137 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Ion batteries required. (included)\"  ],\n  [\"Item model number\",\"‎Rockerz 370\"  ],\n  [\"Compatible Devices\",\"‎Mobile, Laptop and Tablet\"  ],\n  [\"Special Features\",\"‎Android Phone Control;iOS Phone Control;Lightweight;Microphone Feature;Volume-Control\"  ],\n  [\"Mounting Hardware\",\"‎Rockerz 370, Charging Cable, User Manual, Warranty Card\"  ],\n  [\"Number Of Items\",\"‎5\"  ],\n  [\"Microphone Form Factor\",\"‎Yes\"  ],\n  [\"Headphones Form Factor\",\"‎On Ear\"  ],\n  [\"Batteries Included\",\"‎Yes\"  ],\n  [\"Batteries Required\",\"‎Yes\"  ],\n  [\"Battery Cell Composition\",\"‎Lithium\"  ],\n  [\"Cable Feature\",\"‎Without Cable\"  ],\n  [\"Connector Type\",\"‎Wireless\"  ],\n  [\"Maximum Operating Distance\",\"‎10 Metres\"  ],\n  [\"Form Factor\",\"‎On Ear\"  ],\n  [\"Includes Rechargable Battery\",\"‎Yes\"  ],\n  [\"Manufacturer\",\"‎Imagine Marketing Ltd\"  ],\n  [\"Country of Origin\",\"‎China\"  ],\n  [\"Item Weight\",\"‎137 g\"  ]\n]', 999, 60, 40000, 'headphone', NULL, 1400),
(5, 'assets/images/Upload/Tablet/1.png&assets/images/Upload/Tablet/2.png&assets/images/Upload/Tablet/3.png&assets/images/Upload/Tablet/4.png&assets/images/Upload/Tablet/5.png&assets/images/Upload/Tablet/6.png&assets/images/Upload/Tablet/7.png&assets/images/Upl', 'APPLE iPad Air (5th gen)', '2022-05-21', '64 GB ROM 10.9 Inch with Wi-Fi Only (Space Grey).', '[\n  [\"Display\",\"10.9‑inch Liquid Retina display with True Tone\"  ],\n  [\"Capacity\",\"64GB, 256GB\"  ],\n  [\"Chip\",\"Apple M1 chip with 64-bit desktop-class architecture with 8-core CPU, 8-core GPU, Next-generation Neural Engine\"  ],\n  [\"Camera and Video\",\"12MP Wide camera with Smart HDR 3 and 4K video recording at 24 fps, 25 fps, 30 fps, or 60 fps\"  ],\n  [\"Front Camera\",\"12MP Ultra Wide front camera with Center Stage and Smart HDR\"  ],\n  [\"Battery Life\",\"Up to 10 hours of surﬁng the web on Wi‑Fi or watching video.\"  ],\n  [\"Connector\",\"USB-C\"  ],\n  [\"In the Box\",\"iPad Air, USB-C Charge Cable (1 meter), 20W USB-C Power Adapter\"  ],\n  [\"Warranty\",\"Apple-branded hardware product and accessories contained in the original packaging (“Apple Product”) come with a One-Year Limited Warranty.\"  ],\n  [\"Height\",\"9.74  inches (247.6 mm)\"  ],\n  [\"Width\",\"7.02 inches (178.5 mm)\"  ],\n  [\"Depth\",\"0.24 inch (6.1 mm)\"  ],\n  [\"Weight\",\"1.0 pound (458 grams) Wi-Fi model, 1.01 pounds (460 grams) Wi-Fi + Cellular model\"  ],\n  [\"Compatiblity\",\"Apple Pencil (2nd Generation), Smart Keyboard Folio and Magic Keyboard\"  ],\n  [\"Release Date\",\"March 2022\"  ]\n]', 54990, 60, 40000, 'tablet', NULL, 60000),
(6, 'assets/images/Upload/Headphones/headphones/2/1.png&assets/images/Upload/Headphones/headphones/2/2.png&assets/images/Upload/Headphones/headphones/2/3.png&assets/images/Upload/Headphones/headphones/2/4.png&assets/images/Upload/Headphones/headphones/2/5.png', 'BoAt Rockerz 510 Bluetooth Wireless Headphones', '2017-07-26', 'boAt Rockerz 510 Bluetooth Wireless Over Ear Headphones With Mic With Upto 20 Hours Playback, 50Mm Drivers, Padded Ear Cushions And Dual Modes(Furious Blue)', '[\n  [\"Manufacturer\",\"‎Imagine Marketing Ltd, info@imaginemarketingindia.com\"  ],\n  [\"Model\",\"‎Rockerz-510\"  ],\n  [\"Model Name\",\"‎Rockerz\"  ],\n  [\"Product Dimensions\",\"‎7.5 x 20 x 19 cm; 230 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Polymer batteries required. (included)\"  ],\n  [\"Item model number\",\"‎rockerz-510\"  ],\n  [\"Hardware Platform\",\"‎PC, Tablet, Smartphone\"  ],\n  [\"Compatible Devices\",\"‎Mobile, Laptop and Tablet\"  ],\n  [\"Special Features\",\"‎Wireless\"  ],\n  [\"Mounting Hardware\",\"‎Rockerz 510, Charging Cable, User Manual, Warranty Card\"  ],\n  [\"Number Of Items\",\"‎4\"  ],\n  [\"Microphone Form Factor\",\"‎Yes\"  ],\n  [\"Headphones Form Factor\",\"‎On Ear\"  ],\n  [\"Battery Average Life\",\"‎20 Hours\"  ],\n  [\"Batteries Included\",\"‎Yes\"  ],\n  [\"Batteries Required\",\"‎Yes\"  ],\n  [\"Battery Cell Composition\",\"‎Lithium Polymer\"  ],\n  [\"Cable Feature\",\"‎Without Cable\"  ],\n  [\"Connector Type\",\"‎Wireless\"  ],\n  [\"Material\",\"‎Faux Leather, Aluminium\"  ],\n  [\"Maximum Operating Distance\",\"‎10 Metres\"  ],\n  [\"Form Factor\",\"‎Over-Ear\"  ],\n  [\"Includes Rechargable Battery\",\"‎Yes\"  ],\n  [\"Manufacturer\",\"‎Imagine Marketing Ltd\"  ],\n  [\"Country of Origin\",\"‎China\"  ],\n  [\"Item Weight\",\"‎230 g\"  ]\n]', 1399, 59, 4000, 'Headphone', 'boAt & Without Cable & Jazzy Blue & Wireless & On Ear & 230 grams & Sound Isolation', 15000),
(7, 'assets/images/Upload/Headphones/headphones/3/1.png&assets/images/Upload/Headphones/headphones/3/2.png&assets/images/Upload/Headphones/headphones/3/3.png&assets/images/Upload/Headphones/headphones/3/4.png&assets/images/Upload/Headphones/headphones/3/5.png', 'boAt Rockerz 550', '2020-12-23', 'boAt Rockerz 550 Upto 20 Hours Playback, 50MM Drivers, Soft Padded Ear Cushions and Physical Noise Isolation Bluetooth Wireless Over Ear Headphones with Mic (Army Green)', '[\n  [\"Manufacturer\",\"‎Imagine Marketing Ltd, info@imaginemarketingindia.com\"  ],\n  [\"Model\",\"‎Rockerz 550\"  ],\n  [\"Model Name\",\"‎Rockerz 550\"  ],\n  [\"Product Dimensions\",\"‎8.6 x 19.1 x 16.2 cm; 245 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Ion batteries required. (included)\"  ],\n  [\"Item model number\",\"‎Rockerz 550\"  ],\n  [\"Compatible Devices\",\"‎Mobile, Laptop and Tablet\"  ],\n  [\"Special Features\",\"‎Android Phone Control;iOS Phone Control;Microphone Feature\"  ],\n  [\"Mounting Hardware\",\"‎Rockerz 550, Charging Cable, User Manual, Warranty Card\"  ],\n  [\"Number Of Items\",\"‎5\"  ],\n  [\"Microphone Form Factor\",\"‎Yes\"  ],\n  [\"Headphones Form Factor\",\"‎Over Ear\"  ],\n  [\"Batteries Included\",\"‎Yes\"  ],\n  [\"Batteries Required\",\"‎Yes\"  ],\n  [\"Battery Cell Composition\",\"‎Lithium Ion\"  ],\n  [\"Cable Feature\",\"‎Without Cable\"  ],\n  [\"Connector Type\",\"‎Wireless\"  ],\n  [\"Maximum Operating Distance\",\"‎10 Metres\"  ],\n  [\"Form Factor\",\"‎Over-Ear\"  ],\n  [\"Includes Rechargable Battery\",\"‎Yes\"  ],\n  [\"Manufacturer\",\"‎Imagine Marketing Ltd\"  ],\n  [\"Country of Origin\",\"‎China\"  ],\n  [\"Item Weight\",\"‎245 g\"  ]\n]', 1999, 60, 50000, 'Headphone', 'boAt & Without Cable & Army Green & Wireless & Over Ear & 245 grams & Sound Isolation', 4999),
(8, 'assets/images/Upload/Headphones/headphones/4/1.png&assets/images/Upload/Headphones/headphones/4/2.png&assets/images/Upload/Headphones/headphones/4/3.png&assets/images/Upload/Headphones/headphones/4/4.png&assets/images/Upload/Headphones/headphones/4/5.png', 'OMEN Blast Headset', '2020-12-23', 'OMEN Blast Headset | Gaming Headset with Retractable, Noise Canceling Microphone and 7.1 Surround Sound | Multi-Compatible Xbox One, PS4, and PC Headset | USB Headset | (1A858AA)', '[\n  [\"Manufacturer\",\"‎Hewlett Packard\"  ],\n  [\"Model\",\"‎1A858AA#ABL\"  ],\n  [\"Model Name\",\"‎OMEN Blast\"  ],\n  [\"Model Year\",\"‎2020\"  ],\n  [\"Product Dimensions\",\"‎22 x 19.89 x 11.71 cm; 421.84 Grams\"  ],\n  [\"Item model number\",\"‎1A858AA#ABL\"  ],\n  [\"Hardware Platform\",\"‎PC\"  ],\n  [\"Special Features\",\"‎Surround Sound, Noise Cancellation, Noise Isolation, Microphone Feature, Gaming\"  ],\n  [\"Mounting Hardware\",\"‎OMEN Blast Headset, Digital to Analog Converter (DAC), Quick Start guide, Product notices, Warranty\"  ],\n  [\"Number Of Items\",\"‎1\"  ],\n  [\"Microphone Technology\",\"‎Unidirectional\"  ],\n  [\"Headphones Form Factor\",\"‎Over Ear\"  ],\n  [\"Power Source\",\"‎Corded Electric\"  ],\n  [\"Batteries Included\",\"‎No\"  ],\n  [\"Batteries Required\",\"‎No\"  ],\n  [\"Connector Type\",\"‎Wired\"  ],\n  [\"Material\",\"‎Plastic\"  ],\n  [\"Manufacturer\",\"‎Hewlett Packard\"  ],\n  [\"Item Weight\",\"‎422 g\"  ]\n]', 2000, 60, 5000, 'Headphone', 'Omen Blast & HP & Wired & Black & Over Ear ', 2999),
(9, 'assets/images/Upload/Headphones/headphones/6/1.png&assets/images/Upload/Headphones/headphones/6/2.png&assets/images/Upload/Headphones/headphones/6/3.png&assets/images/Upload/Headphones/headphones/6/4.png&assets/images/Upload/Headphones/headphones/6/5.png', 'Sony WH-CH710N Active Noise Cancelling Wireless Headphones', '2020-05-05', 'Sony WH-CH710N Active Noise Cancelling Wireless Headphones Bluetooth Over The Ear Headset with Mic for Phone-Call, 35Hrs Battery Life, Aux, Quick Charge and Google Assistant Support for Mobiles -Black', '[\n  [\"Manufacturer\",\"‎Sony, Sony Corporation, 1-7-1, Konan, Minato-ku, Tokyo, 108-0075, Japan , For product related query call tollfree 18001037799 or email@ Sonyindia.care@sony.com\"  ],\n  [\"Model\",\"‎WH-CH710N/BZIN\"  ],\n  [\"Model Name\",\"‎Headphones\"  ],\n  [\"Product Dimensions\",\"‎22.5 x 20.9 x 24.5 cm; 233 Grams\"  ],\n  [\"Batteries\",\"‎1 A batteries required. (included)\"  ],\n  [\"Item model number\",\"‎WH-CH710N/BZIN\"  ],\n  [\"Hardware Platform\",\"‎Smartphone\"  ],\n  [\"Special Features\",\"‎Noise cancelling\"  ],\n  [\"Mounting Hardware\",\"‎Instruction Manual||USB Cable 1U||Reference Guide 1U\"  ],\n  [\"Number Of Items\",\"‎1\"  ],\n  [\"Microphone Form Factor\",\"‎Built-In\"  ],\n  [\"Headphones Form Factor\",\"‎Over Ear\"  ],\n  [\"Battery Average Life\",\"‎35 Hours\"  ],\n  [\"Batteries Included\",\"‎Yes\"  ],\n  [\"Batteries Required\",\"‎Yes\"  ],\n  [\"Battery Cell Composition\",\"‎Lithium\"  ],\n  [\"Cable Feature\",\"‎Without Cable\"  ],\n  [\"Connector Type\",\"‎Wireless, Bluetooth 5.0\"  ],\n  [\"Has Self Timer\",\"‎No\"  ],\n  [\"Manufacturer\",\"‎Sony\"  ],\n  [\"Country of Origin\",\"‎Vietnam\"  ],\n  [\"Item Weight\",\"‎233 g\"  ]\n]', 8400, 60, 5000, 'Headphone', 'Sony & Without Cable & Black & Wireless & Bluetooth 5.9 & Over Ear & Bluetooth & 233 grams & Active Noise Cancellation', 14000),
(10, 'assets/images/Upload/Laptop/laptops/2/1.png&assets/images/Upload/Laptop/laptops/2/2.png&assets/images/Upload/Laptop/laptops/2/3.png&assets/images/Upload/Laptop/laptops/2/4.png&assets/images/Upload/Laptop/laptops/2/5.png', 'Dell Alienware M15 Gaming Laptop', '2021-07-05', 'Dell Alienware M15 Gaming Laptop|15.6\' 165Hz FHD Display| AMD Ryzen R7 | Nvidia RTX 3060 GFX 6GB GDDR6|16GB + 512GB SSD| RGB Keyboard | Windows 11+MS Office, 2.42kg', '[\n  [\"Manufacturer\",\"‎Dell Computers, Dell India Pvt Ltd\"  ],\n  [\"Series\",\"‎Alienware M15 Ryzen\"  ],\n  [\"Colour\",\"‎Dark Side of the Moon\"  ],\n  [\"Form Factor\",\"‎Netbook\"  ],\n  [\"Item Height\",\"‎25 Millimeters\"  ],\n  [\"Item Width\",\"‎35.7 Centimeters\"  ],\n  [\"Standing screen display size\",\"‎15.6 Inches\"  ],\n  [\"Resolution\",\"‎1920x1080\"  ],\n  [\"Product Dimensions\",\"‎27.2 x 35.7 x 2.5 cm; 2.42 Kilograms\"  ],\n  [\"Batteries\",\"‎1 Lithium Ion batteries required. (included)\"  ],\n  [\"Item model number\",\"‎C780001WIN8\"  ],\n  [\"Processor Brand\",\"‎AMD\"  ],\n  [\"Processor Type\",\"‎Ryzen 7\"  ],\n  [\"Processor Speed\",\"‎4.4 GHz\"  ],\n  [\"Processor Count\",\"‎1\"  ],\n  [\"RAM Size\",\"‎16 GB\"  ],\n  [\"Memory Technology\",\"‎DDR4\"  ],\n  [\"Computer Memory Type\",\"‎DDR4 SDRAM\"  ],\n  [\"Maximum Memory Supported\",\"‎32 GB\"  ],\n  [\"Memory Clock Speed\",\"‎3200 MHz\"  ],\n  [\"Hard Drive Size\",\"‎512 GB\"  ],\n  [\"Hard Disk Description\",\"‎SSD\"  ],\n  [\"Hard Drive Interface\",\"‎USB 3.2\"  ],\n  [\"Graphics Chipset Brand\",\"‎AMD\"  ],\n  [\"Graphics Card Description\",\"‎Dedicated\"  ],\n  [\"Graphics RAM Type\",\"‎DDR SDRAM\"  ],\n  [\"Graphics Card Ram Size\",\"‎6 GB\"  ],\n  [\"Graphics Card Interface\",\"‎PCI Express\"  ],\n  [\"Connectivity Type\",\"‎Bluetooth, Wi-Fi\"  ],\n  [\"Wireless Type\",\"‎Bluetooth, 802.11ax\"  ],\n  [\"Number of USB 2.0 Ports\",\"‎3\"  ],\n  [\"Number of USB 3.0 Ports\",\"‎1\"  ],\n  [\"Optical Drive Type\",\"‎DVD\"  ],\n  [\"Operating System\",\"‎Windows 11\"  ],\n  [\"Are Batteries Included\",\"‎Yes\"  ],\n  [\"Lithium Battery Energy Content\",\"‎84 Watt Hours\"  ],\n  [\"Number Of Lithium Ion Cells\",\"‎6\"  ],\n  [\"Included Components\",\"‎‎Laptop, Battery, Adaptor, User Manual\"  ],\n  [\"Manufacturer\",\"‎Dell Computers\"  ],\n  [\"Country of Origin\",\"‎India\"  ],\n  [\"Item Weight\",\"‎2 kg 420 g\"  ]\n]', 139000, 60, 50000, 'Laptop', 'Dell & Alienware M15 Ryzen & 15.6 Inches & Dark Side of the Moon & 512 GB & Ryzen 7 & 16GB & Windows 11 & Gaming Laptop & NVIDIA RTX Graphics Card RTX 3060', 188284),
(11, 'assets/images/Upload/Laptop/laptops/3/1.png&assets/images/Upload/Laptop/laptops/3/2.png&assets/images/Upload/Laptop/laptops/3/3.png&assets/images/Upload/Laptop/laptops/3/4.png&assets/images/Upload/Laptop/laptops/3/5.png', 'AORUS 17X (YB) Extreme Gaming Laptop', '2021-07-05', 'AORUS 17X (YB) Extreme Gaming Laptop, Lightest+Coolest in Class, 17.3-inch 240Hz IPS, GeForce RTX 2080 Super Max-P, Intel i9-10980HK, 32GB DDR4, 1TB NVMe SSD + 2TB 7200rpm HDD, Overclockable', '[\n  [\"Screen Resolution\",\"‎1920 x 1080 pixels\"  ],\n  [\"Max Screen Resolution\",\"‎1920 x 1080 Pixels\"  ],\n  [\"Processor\",\"‎5.3 GHz intel_core_i9\"  ],\n  [\"RAM\",\"‎32 GB DDR4\"  ],\n  [\"Memory Speed\",\"‎3200\"  ],\n  [\"Hard Drive\",\"‎2 TB 2TB SATA HDD (7200RPM)\"  ],\n  [\"Graphics Coprocessor\",\"‎NVIDIA GeForce RTX 2080\"  ],\n  [\"Chipset Brand\",\"‎NVIDIA\"  ],\n  [\"Card Description\",\"‎Dedicated\"  ],\n  [\"Graphics Card Ram Size\",\"‎8 GB\"  ],\n  [\"Wireless Type\",\"‎Bluetooth, 802.11ax, 802.11ac\"  ],\n  [\"Number of USB 3.0 Ports\",\"‎4\"  ],\n  [\"Average Battery Life (in hours)\",\"‎24 Hours\"  ],\n  [\"National Stock Number\",\"‎AORUS 17X YB-9US2452MP\"  ],\n  [\"Brand\",\"‎GIGABYTE\"  ],\n  [\"Series\",\"‎AORUS 17X YB-9US2452MP\"  ],\n  [\"Item model number\",\"‎AORUS 17X\"  ],\n  [\"Hardware Platform\",\"‎PC\"  ],\n  [\"Operating System\",\"‎Windows 10 Pro\"  ],\n  [\"Item Weight\",\"‎8.26 pounds\"  ],\n  [\"Product Dimensions\",\"‎15.59 x 11.53 x 1.49 inches\"  ],\n  [\"Item Dimensions  LxWxH\",\"‎15.59 x 11.53 x 1.49 inches\"  ],\n  [\"Color\",\"‎17.3\\\" | AORUS 17X - Extreme Performance\"  ],\n  [\"Processor Brand\",\"‎Intel\"  ],\n  [\"Processor Count\",\"‎8\"  ],\n  [\"Computer Memory Type\",\"‎DDR4 SDRAM\"  ],\n  [\"Flash Memory Size\",\"‎1\"  ],\n  [\"Optical Drive Type\",\"‎No Optical Drive\"  ],\n  [\"Power Source\",\"‎Battery Powered\"  ],\n  [\"Voltage\",\"‎120 Volts\"  ],\n  [\"Batteries\",\"‎1 Lithium Polymer batteries required. (included)\"  ]\n]', 221000, 80, 4000, 'Laptop', 'GIGABYTE & AORUS 17X YB-9US2452MP &	17.3 Inches & 17.3\" & AORUS 17X - Extreme Performance & 2 TB & Intel Core i9 & 32 GB & Windows 10 Pro & Dedicated Card & NVIDIA GeForce RTX 2080 ', 288284),
(12, 'assets/images/Upload/Laptop/laptops/4/1.png&assets/images/Upload/Laptop/laptops/4/2.png&assets/images/Upload/Laptop/laptops/4/3.png&assets/images/Upload/Laptop/laptops/4/4.png', 'HP OMEN | 15-EN0023DX', '2020-07-31', 'HP OMEN | 15-EN0023DX/Gaming 15.6\" Laptop | AMD Ryzen 7/4800H | 16GB DDR4 3200/MHz | 1TB PCIe NVMe M.2 SSD | NVIDIA GeForce GTX 1660 Ti | Backlit Keyboard/Windows 10 Home', '[\n  [\"Manufacturer\",\"‎hp\"  ],\n  [\"Series\",\"‎15-EN0023DX\"  ],\n  [\"Colour\",\"‎Mica Silver\"  ],\n  [\"Form Factor\",\"‎Laptop\"  ],\n  [\"Item Height\",\"‎0.9 Inches\"  ],\n  [\"Item Width\",\"‎9.4 Inches\"  ],\n  [\"Standing screen display size\",\"‎15.6 Inches\"  ],\n  [\"Resolution\",\"‎1920 x 1080 Pixels\"  ],\n  [\"Product Dimensions\",\"‎35.56 x 23.88 x 2.29 cm; 2.5 Kilograms\"  ],\n  [\"Batteries\",\"‎1 Lithium Metal batteries required.\"  ],\n  [\"Item model number\",\"‎15-EN0023DX\"  ],\n  [\"Processor Brand\",\"‎AMD\"  ],\n  [\"Processor Type\",\"‎AMD Ryzen 7\"  ],\n  [\"Processor Speed\",\"‎2.9 GHz\"  ],\n  [\"Processor Count\",\"‎8\"  ],\n  [\"RAM Size\",\"‎16 GB\"  ],\n  [\"Memory Technology\",\"‎DIMM\"  ],\n  [\"Computer Memory Type\",\"‎DDR4 SDRAM\"  ],\n  [\"Memory Clock Speed\",\"‎3200 MHz\"  ],\n  [\"Hard Drive Size\",\"‎1 TB\"  ],\n  [\"Hard Disk Description\",\"‎SSD\"  ],\n  [\"Hard Drive Interface\",\"‎Solid State\"  ],\n  [\"Audio Details\",\"‎Headphones, Speakers\"  ],\n  [\"Graphics Coprocessor\",\"‎NVIDIA GeForce GTX 1660Ti\"  ],\n  [\"Graphics Chipset Brand\",\"‎NVIDIA\"  ],\n  [\"Graphics Card Description\",\"‎Dedicated\"  ],\n  [\"Graphics RAM Type\",\"‎DDR4 SDRAM\"  ],\n  [\"Graphics Card Ram Size\",\"‎6 GB\"  ],\n  [\"Graphics Card Interface\",\"‎Integrated\"  ],\n  [\"Connectivity Type\",\"‎Wi-Fi\"  ],\n  [\"Wireless Type\",\"‎Bluetooth\"  ],\n  [\"Number of USB 2.0 Ports\",\"‎1\"  ],\n  [\"Number of HDMI Ports\",\"‎1\"  ],\n  [\"Power Source\",\"‎AC & Battery\"  ],\n  [\"Hardware Platform\",\"‎PC\"  ],\n  [\"Operating System\",\"‎Windows 10 Home\"  ],\n  [\"Are Batteries Included\",\"‎No\"  ],\n  [\"Lithium Battery Energy Content\",\"‎70.9 Watt Hours\"  ],\n  [\"Lithium Battery Weight\",\"‎0.85 Grams\"  ],\n  [\"Number Of Lithium Ion Cells\",\"‎3\"  ],\n  [\"Manufacturer\",\"‎hp\"  ],\n  [\"Item Weight\",\"‎2 kg 500 g\"  ]\n]', 129000, 80, 10000, 'Laptop', '\r\nHP & 15-EN0023DX & 15.6 Inches & Mica Silver & 1 TB & AMD Ryzen 7 & 16 GB & Windows 10 Home & Webcam & Backlit Keyboard & Dedicated Card', 159994),
(13, 'assets/images/Upload/Laptop/laptops/5/1.png&assets/images/Upload/Laptop/laptops/5/2.png&assets/images/Upload/Laptop/laptops/5/3.png&assets/images/Upload/Laptop/laptops/5/4.png', 'HP Omen 16 Premium Gaming Laptop', '2022-01-04', 'HP Omen 16 Premium Gaming Laptop I 16.1” Full HD IPS 144Hz 7ms I 11th Gen Intel 8-Core i7-11800H I 64GB DDR4 1TB SSD I Geforce RTX 3060 6GB I Thunderbolt Backlit WiFi6E Win11 + 32GB MicroSD Card', '[\n  [\"Manufacturer\",\"‎hp\"  ],\n  [\"Series\",\"‎HP Omen 16 144Hz i7 3060\"  ],\n  [\"Colour\",\"‎Black\"  ],\n  [\"Form Factor\",\"‎Laptop\"  ],\n  [\"Item Height\",\"‎0.91 Inches\"  ],\n  [\"Item Width\",\"‎14.54 Inches\"  ],\n  [\"Standing screen display size\",\"‎16.1 Inches\"  ],\n  [\"Screen Resolution\",\"‎1920x1080\"  ],\n  [\"Resolution\",\"‎Full HD (1920 x 1080) IPS 144Hz 7ms Pixels\"  ],\n  [\"Product Dimensions\",\"‎24.79 x 36.93 x 2.31 cm; 2.31 Kilograms\"  ],\n  [\"Item model number\",\"‎HP Omen\"  ],\n  [\"Processor Brand\",\"‎Intel\"  ],\n  [\"Processor Speed\",\"‎2.3 GHz\"  ],\n  [\"Processor Count\",\"‎8\"  ],\n  [\"RAM Size\",\"‎64 GB\"  ],\n  [\"Memory Technology\",\"‎DDR4\"  ],\n  [\"Computer Memory Type\",\"‎DDR4 SDRAM\"  ],\n  [\"Hard Drive Size\",\"‎1 TB\"  ],\n  [\"Hard Disk Description\",\"‎SSD\"  ],\n  [\"Hard Drive Interface\",\"‎Solid State\"  ],\n  [\"Audio Details\",\"‎Headphones\"  ],\n  [\"Graphics Coprocessor\",\"‎NVIDIA GeForce RTX 3060 6GB Dedicated\"  ],\n  [\"Graphics Chipset Brand\",\"‎NVIDIA\"  ],\n  [\"Graphics Card Description\",\"‎Dedicated\"  ],\n  [\"Graphics Card Ram Size\",\"‎6 GB\"  ],\n  [\"Connectivity Type\",\"‎Bluetooth\"  ],\n  [\"Wireless Type\",\"‎802.11ax\"  ],\n  [\"Number of HDMI Ports\",\"‎1\"  ],\n  [\"Power Source\",\"‎AC & Battery\"  ],\n  [\"Hardware Platform\",\"‎PC\"  ],\n  [\"Operating System\",\"‎Windows 11\"  ],\n  [\"Manufacturer\",\"‎hp\"  ],\n  [\"Item Weight\",\"‎2 kg 310 g\"  ]\n]', 174000, 80, 30000, 'Laptop', 'HP & 16-b0370TX & 16.1 Inches & Black & Core i7 & 16 GB & Windows 10 Home & NVIDIA® GeForce RTX™ 3070 & Dedicated Card', 200994),
(14, 'assets/images/Upload/Mobiles/mobi/2/1.png&assets/images/Upload/Mobiles/mobi/2/2.png&assets/images/Upload/Mobiles/mobi/2/3.png&assets/images/Upload/Mobiles/mobi/2/4.png&assets/images/Upload/Mobiles/mobi/2/5.png&assets/images/Upload/Mobiles/mobi/2/6.png', 'APPLE iPhone 12 (Purple, 64 GB)', '2021-07-31', 'Dive into a world of crystal-clear visuals with the Super Retina XDR Display of this Apple iPhone 12. This beast of a smartphone packs the A14 Bionic chip to make for blazing-fast performance speeds.', '[\n  [\"Display\",\"6.1-inch (15.5 cm diagonal) Super Retina XDR display with True Tone\"  ],\n  [\"Capacity\",\"64GB, 128GB, 256GB\"  ],\n  [\"Splash, Water, and Dust Resistant\",\"All-glass and surgical-grade stainless steel design, water and dust resistant (rated IP68)\"  ],\n  [\"Camera and Video\",\"Dual 12MP cameras with Portrait mode, Depth Control, Portrait Lighting, Smart HDR, and 4K Dolby Vision HDR video up to 60 fps\"  ],\n  [\"Front Camera\",\"12MP TrueDepth front camera with Portrait mode, Depth Control, Portrait Lighting, and Smart HDR 3\"  ],\n  [\"Power and Battery\",\"Video playback:Up to 17 hours, Video playback (streamed):Up to 11 hours, Audio playback:Up to 65 hours, 20W adapter or higher (sold separately), Fast-charge capable: Up to 50% charge in around 30 minutes with 20W adapter or higher\"  ],\n  [\"In the Box\",\"iPhone with iOS 14, USB-C to Lightning Cable,  Documentation\"  ],\n  [\"Warranty\",\"1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase\"  ],\n  [\"Height\",\"5.78 inches (146.7 mm)\"  ],\n  [\"Width\",\"2.82 inches (71.5 mm)\"  ],\n  [\"Depth\",\"0.29 inch (7.4 mm)\"  ],\n  [\"Weight\",\"5.78 ounces (164 grams)\"  ]\n]', 60089, 60, 30000, 'Phone', '6 GB RAM & 128 GB ROM & 16.33 cm (6.43 inch) & 64MP Rear Camera & 4500 mAh Battery', 65900),
(15, 'assets/images/Upload/Mobiles/mobi/3/1.png&assets/images/Upload/Mobiles/mobi/3/2.png&assets/images/Upload/Mobiles/mobi/3/3.png&assets/images/Upload/Mobiles/mobi/3/4.png&assets/images/Upload/Mobiles/mobi/3/5.png&assets/images/Upload/Mobiles/mobi/3/6.png', 'OnePlus Nord CE 2 5G (Bahama Blue, 128 GB)  (6 GB RAM)', '2022-02-22', '65W SUPERVOOC – Accelerated charge velocity shall rocket the 4500mAh battery to a days power in 15 minutes. Certified by TÜV Rheinland, one shall “Charge & Play” with absolute peace of mind.', '[\n  [\"RAM\",\"‎6 GB\"  ],\n  [\"Product Dimensions\",\"‎7.3 x 0.8 x 16.1 cm; 173 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Ion batteries required. (included)\"  ],\n  [\"Item model number\",\"‎120010220436\"  ],\n  [\"Wireless communication technologies\",\"‎Wi-Fi\"  ],\n  [\"Connectivity technologies\",\"‎Bluetooth, Wi-Fi, USB\"  ],\n  [\"Special features\",\"‎Fingerprint Scanner, Dual_Sim, Gorilla Glass, Camera, Wifi\"  ],\n  [\"Display technology\",\"‎AMOLED\"  ],\n  [\"Other display features\",\"‎Wireless\"  ],\n  [\"Audio Jack\",\"‎3.5 mm\"  ],\n  [\"Colour\",\"‎Bahamas Blue\"  ],\n  [\"Battery Power Rating\",\"‎4500\"  ],\n  [\"Whats in the box\",\"‎SIM Tray Ejector, Adapter, USB Cable\"  ],\n  [\"Manufacturer\",\"‎Oppo Mobiles India Private Limited\"  ],\n  [\"Country of Origin\",\"‎India\"  ],\n  [\"Item Weight\",\"‎173 g\"  ]\n]', 23999, 80, 20000, 'Phone', 'HP & 16-b0370TX & 16.1 Inches & Black & Core i7 & 16 GB & Windows 10 Home & NVIDIA® GeForce RTX™ 3070 & Dedicated Card', 24999),
(16, 'assets/images/Upload/Mobiles/mobi/4/1.png&assets/images/Upload/Mobiles/mobi/4/2.png&assets/images/Upload/Mobiles/mobi/4/3.png&assets/images/Upload/Mobiles/mobi/4/4.png&assets/images/Upload/Mobiles/mobi/4/5.png', 'OPPO A31 (Mystery Black, 128 GB)  (6 GB RAM)', '2020-01-22', 'This Oppo mobile phone is not just easy on the eyes but it’s also equipped with innovative features. With 6 GB RAM, you can play games and multitask with ease. ', '[\n  [\"RAM\",\"‎6 GB\"  ],\n  [\"Product Dimensions\",\"‎16.4 x 0.8 x 7.6 cm; 180 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Polymer batteries required. (included)\"  ],\n  [\"Item model number\",\"‎CPH2015\"  ],\n  [\"Wireless communication technologies\",\"‎Bluetooth, Wi-Fi\"  ],\n  [\"Connectivity technologies\",\"‎4g\"  ],\n  [\"Special features\",\"‎Acceleration sensor, Magnetic induction, Fingerprint, Proximity Sensor, Dual SIM, OTG, GPS, Pedometer, G-sensor, Light sensor, Other sensors, Video Player, Music Player\"  ],\n  [\"Colours displayed\",\"‎269 ppi pixel density\"  ],\n  [\"Other display features\",\"‎Wireless\"  ],\n  [\"Device interface - primary\",\"‎Touchscreen\"  ],\n  [\"Other camera features\",\"‎Triple Rear Camera (12 MP + 2 MP + 2 MP) | 8 MP Front Camera\"  ],\n  [\"Audio Jack\",\"‎3.5 mm\"  ],\n  [\"Form factor\",\"‎Smartphone\"  ],\n  [\"Colour\",\"‎Mystery Black\"  ],\n  [\"Battery Power Rating\",\"‎4230\"  ],\n  [\"Phone Talk Time\",\"‎45 Hours\"  ],\n  [\"Phone Standby Time (with data)\",\"‎450 Hours\"  ],\n  [\"Whats in the box\",\"‎Handset, USB Cable, Sim Tray Ejecter, Pre-applied Screen Protector and Protective Case, Booklet with Warranty Card and Quick Guide\"  ],\n  [\"Manufacturer\",\"‎OPPO Mobiles India Pvt. Ltd.\"  ],\n  [\"Country of Origin\",\"‎India\"  ],\n  [\"Item Weight\",\"‎180 g\"  ]\n]', 12729, 80, 30000, 'Phone', '6 GB RAM & 128 GB ROM & Expandable Upto 256 GB & 16.51 cm (6.5 inch) & HD+ Display & 12MP + 2MP + 2MP & 8MP Front Camera & 4230 mAh Battery & MediaTek Helio P35 Octa Core Processor', 14499),
(17, 'assets/images/Upload/Mobiles/mobi/5/1.png&assets/images/Upload/Mobiles/mobi/5/2.png&assets/images/Upload/Mobiles/mobi/5/3.png&assets/images/Upload/Mobiles/mobi/5/4.png&assets/images/Upload/Mobiles/mobi/5/5.png&assets/images/Upload/Mobiles/mobi/5/6.png', 'Redmi Note 11 (Horizon Blue, 64 GB)  (4 GB RAM)', '2022-01-11', 'Redmi Note 11 4G is configured with a 6nm Qualcomm Snapdragon 680 chipset and 4GB LPDDR4X RAM. The brand has installed an Adreno 610 GPU in the device that offers a great visual experience. Its internal operations are managed by an Octa-core processor', '[\n  [\"RAM\",\"‎4 GB\"  ],\n  [\"Product Dimensions\",\"‎16 x 0.8 x 7.4 cm; 179 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Polymer batteries required. (included)\"  ],\n  [\"Wireless communication technologies\",\"‎Cellular\"  ],\n  [\"Connectivity technologies\",\"‎Bluetooth, Infrared, Wi-Fi, USB\"  ],\n  [\"GPS\",\"‎True\"  ],\n  [\"Special features\",\"‎Dual Stereo Speakers for immersive audio experience, The display is protected by Corning Gorilla Glass 3, 3.5mm Jack, IR Blaster, Dedicated Micro SD Slot, Z-Axis Linear Vibration Motor, Splash, Water and Dust Resistant- IP53, 50 MP AI Quad Camera Setup 8MP Ultrawide-FOV 118 degrees 2 MP Macro Sensor 2 MP Depth Sensor Portrait | Panaroma | Time Lapse | Pro Mode | Night Mode | Short Video Mode | Ultra wide-angle distortion correction | Custom Watermark | Document mode | HDR | AI scene detection | Video macro mode | Movie frame | Time burst | Google Lens| AI Watermark | Slow Motion\"  ],\n  [\"Display technology\",\"‎AMOLED\"  ],\n  [\"Other display features\",\"‎Wireless\"  ],\n  [\"Device interface - primary\",\"‎Touchscreen\"  ],\n  [\"Other camera features\",\"‎50 MP + 8 MP + 2 MP + 2 MP (quad)\"  ],\n  [\"Audio Jack\",\"‎3.5 mm\"  ],\n  [\"Form factor\",\"‎Bar\"  ],\n  [\"Colour\",\"‎Horizon Blue\"  ],\n  [\"Battery Power Rating\",\"‎5000\"  ],\n  [\"Whats in the box\",\"‎Redmi Note 11, Power adapter, USB cable, SIM eject tool, Warranty card, User guide, Clear soft case, Screen protector pre-applied on the phone\"  ],\n  [\"Manufacturer\",\"‎Redmi\"  ],\n  [\"Country of Origin\",\"‎India\"  ],\n  [\"Item Weight\",\"‎179 g\"  ]\n]', 12834, 60, 40000, 'Phone', '4 GB RAM & 64 GB ROM & Expandable Upto 1 TB & 16.33 cm (6.43 inch) & Full HD+ Display & 50MP + 8MP + 2MP + 2MP & 13MP Front Camera & 5000 mAh Battery & Qualcomm SM6225 Snapdragon 680 Processor', 13093),
(18, 'assets/images/Upload/Mobiles/mobi/6/1.png&assets/images/Upload/Mobiles/mobi/6/2.png&assets/images/Upload/Mobiles/mobi/6/3.png&assets/images/Upload/Mobiles/mobi/6/4.png&assets/images/Upload/Mobiles/mobi/6/5.png', 'SAMSUNG Galaxy S20 FE (Cloud Lavender, 128 GB)  (8 GB RAM)', '2021-03-02', 'If you’re a social media freak, a photography enthusiast, and a gaming geek, and are looking for a device that can help you click amazing photos and play games, then the Samsung Galaxy S20 FE is for you.', '[\n  [\"RAM\",\"‎8 GB\"  ],\n  [\"Product Dimensions\",\"‎0.84 x 7.45 x 15.98 cm; 190 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Ion batteries required. (included)\"  ],\n  [\"Item model number\",\"‎SM-G781BLVGINS\"  ],\n  [\"Connectivity technologies\",\"‎5g\"  ],\n  [\"Special features\",\"‎Rear Camera, Dual_Sim, Camera, Fast Charging, Hybrid Sim Slot\"  ],\n  [\"Display technology\",\"‎AMOLED\"  ],\n  [\"Other display features\",\"‎Wireless\"  ],\n  [\"Other camera features\",\"‎Rear, Front\"  ],\n  [\"Form factor\",\"‎Bar\"  ],\n  [\"Colour\",\"‎Cloud Lavender\"  ],\n  [\"Battery Power Rating\",\"‎4500\"  ],\n  [\"Whats in the box\",\"‎Handset, Non-removable Battery Included, Travel Adapter, USB Cable, User Manual\"  ],\n  [\"Manufacturer\",\"‎Samsung\"  ],\n  [\"Country of Origin\",\"‎India\"  ],\n  [\"Item Weight\",\"‎190 g\"  ]\n]', 50149, 60, 7000, 'Phone', '8 GB RAM & 128 GB ROM & Expandable Upto 1 TB & 16.51 cm (6.5 inch) & Full HD+ Display & 12MP + 12MP + 8MP Rear Camera & 32MP Front Camera & 4500 mAh Lithium Ion Battery & Exynos Octa Core Processor & Super AMOLED Display & 120 Hz Rate & IP68 Rating', 65999),
(19, 'assets/images/Upload/Tablet/tab/1/1.png&assets/images/Upload/Tablet/tab/1/2.png&assets/images/Upload/Tablet/tab/1/3.png&assets/images/Upload/Tablet/tab/1/4.png&assets/images/Upload/Tablet/tab/1/5.png&assets/images/Upload/Tablet/tab/1/6.png', 'APPLE iPad Pro 2021 (3rd Generation)', '2021-12-23', '8 GB RAM 256 GB ROM 11 inches with Wi-Fi+5G (Silver)', '[\n  [\"Display\",\"27.96(11-inch) Liquid Retina display\"  ],\n  [\"Capacity\",\"128GB, 256GB, 512GB, 1TB, 2TB\"  ],\n  [\"Chip\",\"Apple M1 Chip\"  ],\n  [\"Camera and Video\",\"12MP Wide and 10MP Ultra Wide cameras with Smart HDR and 4K video at 24 fps, 25fps, 30 fps, or 60 fps\"  ],\n  [\"Front Camera\",\"12MP TrueDepth front camera with Portrait mode, Portratit Lighting and Smart HDR\"  ],\n  [\"Battery Life\",\"Up to 10 hours of surfing the web on Wi‑Fi or watching video. Up to 9 hours of surfing the web using a mobile data network\"  ],\n  [\"Connector\",\"USB‑C connector with support for Thunderbolt / USB 4\"  ],\n  [\"In the Box\",\"iPad Pro USB‑C Charge Cable (1 metre) 20W USB‑C Power Adapter\"  ],\n  [\"Warranty\",\"Apple-branded hardware product and accessories contained in the original packaging (“Apple Product”) come with a One-Year Limited Warranty. See apple.com/in/legal/warranty for more information.\"  ],\n  [\"Height\",\"247.6 mm (9.74 inches)\"  ],\n  [\"Width\",\"178.5 mm (7.02 inches)\"  ],\n  [\"Depth\",\"5.9 mm (0.23 inches)\"  ],\n  [\"Weight\",\"466 grams (1.03 pounds) Wi‑Fi model. 468 grams (1.03 pounds) Wi‑Fi + Cellular models\"  ],\n  [\"Compatiblity\",\"Apple Pencil (2nd Generation), Magic Keyboard, Smart Keyboard Folio\"  ],\n  [\"Release Date\",\"May- 2021\"  ]\n]', 94900, 60, 38490, 'Tablet', 'Apple M1 chip & 11-inch & Liquid Retina display & P3 wide color & TrueDepth camera system & 12MP Wide camera & 10MP Ultra Wide Camera & LiDAR Scanner & 5G & high-quality & Wi-Fi 6 & external storage & displays & docks & Apple Pay & Apple Pencil (2nd genera', 99999),
(20, 'assets/images/Upload/Tablet/tab/2/1.png&assets/images/Upload/Tablet/tab/2/2.png&assets/images/Upload/Tablet/tab/2/3.png&assets/images/Upload/Tablet/tab/2/4.png&assets/images/Upload/Tablet/tab/2/5.png&assets/images/Upload/Tablet/tab/2/6.png', 'Lenovo Tab M10 FHD Plus (2nd Gen)', '2021-10-15', '4 GB RAM 128 GB ROM 10.3 inches with Wi-Fi Only Tablet (Platinum Grey)', '[\n  [\"Manufacturer\",\"‎Lenovo, Motorola (Wuhan) Mobility Technologies Comillimetersunication Ltd., No. 19, Gaoxin 4th Road,East Lake High-Tech Zone, Wuhan Hubei P.R. China\"  ],\n  [\"Model\",\"‎Lenovo Tab M10 FHD Plus\"  ],\n  [\"Model Name\",\"‎Lenovo Tab M10 FHD Plus\"  ],\n  [\"Product Dimensions\",\"‎24.4 x 0.8 x 15.3 cm; 460 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Ion batteries required. (included)\"  ],\n  [\"Item model number\",\"‎Lenovo Tab M10 FHD Plus\"  ],\n  [\"RAM Size\",\"‎4 GB\"  ],\n  [\"Memory Storage Capacity\",\"‎128 GB\"  ],\n  [\"Memory Slots Available\",\"‎128GB\"  ],\n  [\"Flash Memory Installed Size\",\"‎128\"  ],\n  [\"Ram Memory Installed Size\",\"‎4 GB\"  ],\n  [\"Operating System\",\"‎Android\"  ],\n  [\"Processor Brand\",\"‎4 x A53 @ 2.3GHz, 4 x A53 @ 1.8GHz MediaTek Helio P22T Tab\"  ],\n  [\"Processor Speed\",\"‎2.3 GHz\"  ],\n  [\"Processor Count\",\"‎8\"  ],\n  [\"Special Features\",\"‎Single SIM, GPS\"  ],\n  [\"Mounting Hardware\",\"‎Tablet, Adapter, USB Type C, Quick Start Guide, User Guide\"  ],\n  [\"Standing screen display size\",\"‎10.3 Inches\"  ],\n  [\"Display Type\",\"‎1920 X 1200\"  ],\n  [\"Screen Resolution\",\"‎1920 x 1200 pixels\"  ],\n  [\"Batteries Included\",\"‎Yes\"  ],\n  [\"Batteries Required\",\"‎Yes\"  ],\n  [\"Battery Cell Composition\",\"‎Lithium Ion\"  ],\n  [\"Battery Power Rating\",\"‎5000\"  ],\n  [\"Cellular Technology\",\"‎Wi-Fi\"  ],\n  [\"Connector Type\",\"‎Cellular\"  ],\n  [\"Material\",\"‎Metal\"  ],\n  [\"Form Factor\",\"‎Touchscreen Phone\"  ],\n  [\"Manufacturer\",\"‎Lenovo\"  ],\n  [\"Item Weight\",\"‎460 g\"  ]\n]', 15999, 60, 83780, 'Tablet', '4 GB RAM & 128 GB ROM & Expandable Upto 256 GB & 26.16 cm (10.3 inches) & Full HD Display & 8 MP Primary Camera & 5 MP Front & Android 9 (Pie) & Battery: 5000 mAh & Processor: Octa Core ', 30000),
(21, 'assets/images/Upload/Tablet/tab/3/1.png&assets/images/Upload/Tablet/tab/3/2.png&assets/images/Upload/Tablet/tab/3/3.png&assets/images/Upload/Tablet/tab/3/4.png&assets/images/Upload/Tablet/tab/3/5.png&assets/images/Upload/Tablet/tab/3/6.png', 'Lenovo Yoga Smart Tab', '2021-05-28', 'Lenovo Yoga Smart Tab with Google Assistant 4 GB RAM 64 GB ROM 10.1 inch with Wi-Fi+4G Tablet (Iron Grey)', '[\n  [\"RAM\",\"‎4 GB\"  ],\n  [\"Product Dimensions\",\"‎24.2 x 0.6 x 16.6 cm; 580 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Ion batteries required. (included)\"  ],\n  [\"Item model number\",\"‎Yoga Smart Tab with the Google Assistant\"  ],\n  [\"Wireless communication technologies\",\"‎Bluetooth, Wi-Fi\"  ],\n  [\"Connectivity technologies\",\"‎Cellular\"  ],\n  [\"Special features\",\"‎Single SIM, GPS\"  ],\n  [\"Display resolution\",\"‎1920 x 1200 pixels\"  ],\n  [\"Other display features\",\"‎Personal Computer\"  ],\n  [\"Other camera features\",\"‎5MP\"  ],\n  [\"Form factor\",\"‎Touchscreen Phone\"  ],\n  [\"Colour\",\"‎Iron Grey\"  ],\n  [\"Battery Power Rating\",\"‎7000\"  ],\n  [\"Whats in the box\",\"‎1N Lenovo Yoga Smart Tab, 1N 5V/2A Adapter, 1N USB Type-C 2.0, 1N Quick Start Guide, 1N User Guide\"  ],\n  [\"Manufacturer\",\"‎Lenovo\"  ],\n  [\"Country of Origin\",\"‎China\"  ],\n  [\"Imported By\",\"‎Imported by; Levono India Pvt Ltd RBD (Ferns Icon) Level 2, Doddenakundi Village, Marathalli ORR, K R Puram Hobli Bengaluru – 560037\"  ],\n  [\"Item Weight\",\"‎580 g\"  ]\n]', 19999, 60, 28300, 'Tablet', '4 GB RAM & 64 GB ROM & Expandable Upto 256 GB & 25.65 cm (10.1 inch) & Full HD Display & 8 MP Primary Camera & 5 MP Front & Android 10 & Battery: 7000 mAh & Processor: Qualcomm Snapdragon 439', 35500),
(22, 'assets/images/Upload/Tablet/tab/4/1.png&assets/images/Upload/Tablet/tab/4/2.png&assets/images/Upload/Tablet/tab/4/3.png&assets/images/Upload/Tablet/tab/4/4.png&assets/images/Upload/Tablet/tab/4/5.png&assets/images/Upload/Tablet/tab/4/6.png', 'Nokia Tab T20', '2022-02-01', 'Nokia Tab T20 3GB RAM 32GB ROM 10.36 inch with Wi-Fi Only Tablet (Blue)', '[\n  [\"Manufacturer\",\"‎Emdoor Digital, Padget Electronics Private Limited, B-17 and 18, Phase-II, Noida, 201305, Uttar Pradesh, India\"  ],\n  [\"Series\",\"‎NOKIA T20 LTE 4/64 IN BLUE\"  ],\n  [\"Colour\",\"‎Blue\"  ],\n  [\"Item Height\",\"‎8 Millimeters\"  ],\n  [\"Item Width\",\"‎15.7 Centimeters\"  ],\n  [\"Standing screen display size\",\"‎10.36 Inches\"  ],\n  [\"Screen Resolution\",\"‎1200 x 2000 pixels\"  ],\n  [\"Resolution\",\"‎1200 x 2000 Pixels\"  ],\n  [\"Product Dimensions\",\"‎24.8 x 15.7 x 0.8 cm; 470 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Ion batteries required. (included)\"  ],\n  [\"Item model number\",\"‎Nokia T20\"  ],\n  [\"Processor Brand\",\"‎Unisoc\"  ],\n  [\"Processor Count\",\"‎8\"  ],\n  [\"RAM Size\",\"‎4 GB\"  ],\n  [\"Speaker Description\",\"‎Stereo Speakers\"  ],\n  [\"Graphics Coprocessor\",\"‎Mali G52 3EE\"  ],\n  [\"Graphics Chipset Brand\",\"‎ARM\"  ],\n  [\"Graphics Card Description\",\"‎Integrated\"  ],\n  [\"Connectivity Type\",\"‎Cellular\"  ],\n  [\"Wireless Type\",\"‎802.11n, 802.11b, 802.11a, 802.11g\"  ],\n  [\"Rear Webcam Resolution\",\"‎8 MP\"  ],\n  [\"Front Webcam Resolution\",\"‎5 MP\"  ],\n  [\"Operating System\",\"‎Android 11\"  ],\n  [\"Are Batteries Included\",\"‎Yes\"  ],\n  [\"Number Of Lithium Ion Cells\",\"‎1\"  ],\n  [\"Included Components\",\"‎Device, Type-c cable, Charger, QSG, Safety booklet, Warranty card, SIM PIN, SIM PIN Sticker, User guide band, Plastic bag\"  ],\n  [\"Manufacturer\",\"‎Emdoor Digital\"  ],\n  [\"Country of Origin\",\"‎India\"  ],\n  [\"Item Weight\",\"‎470 g\"  ]\n]', 15499, 60, 23780, 'Tablet', '3GB RAM & 32GB ROM & Expandable Upto 512 GB & 26.31 cm & 2K Display & 8 MP Primary Camera & 5 MP Front & Android 11 & Battery: 8200 mAh & Processor: Unisoc T610', 17999),
(23, 'assets/images/Upload/Tablet/tab/5/1.png&assets/images/Upload/Tablet/tab/5/2.png&assets/images/Upload/Tablet/tab/5/3.png&assets/images/Upload/Tablet/tab/5/4.png&assets/images/Upload/Tablet/tab/5/5.png&assets/images/Upload/Tablet/tab/5/6.png', 'Samsung Galaxy Tab A8', '2022-01-16', 'Samsung Galaxy Tab A8 26.69 cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi+LTE Tablet, Gray, (SM-X205NZAEINU)', '[\n  [\"Manufacturer\",\"‎Samsung, Dongguan Huabel Electronic  Technology Co., Ltd. Songshanlake,Branch NO. 8 INDUSTRIAL NORTHERN NO.1 ROAD, SONGSHANLAKE NATIONAL HIGH-TECH INDUSTRIAL DEVELOPMENT ZONE, DONGGUAN CITY, GUANGDONG PROVINCE CHINA, GUANGDONG ,CHINA -523808\"  ],\n  [\"Series\",\"‎SM-X205NZAEINU\"  ],\n  [\"Colour\",\"‎Gray\"  ],\n  [\"Item Height\",\"‎16.2 Centimeters\"  ],\n  [\"Item Width\",\"‎24.7 Centimeters\"  ],\n  [\"Standing screen display size\",\"‎26.69 Centimetres\"  ],\n  [\"Resolution\",\"‎1920x1200 (WUXGA) Pixels\"  ],\n  [\"Product Dimensions\",\"‎0.7 x 24.7 x 16.2 cm; 508 Grams\"  ],\n  [\"Batteries\",\"‎1 Lithium Ion batteries required. (included)\"  ],\n  [\"Item model number\",\"‎SM-X205NZAEINU\"  ],\n  [\"Processor Brand\",\"‎Unisoc\"  ],\n  [\"Processor Speed\",\"‎2 GHz\"  ],\n  [\"RAM Size\",\"‎4 GB\"  ],\n  [\"Speaker Description\",\"‎Dolby Atmos\"  ],\n  [\"Graphics Card Description\",\"‎Integrated\"  ],\n  [\"Connectivity Type\",\"‎Cellular, Wi-Fi\"  ],\n  [\"Rear Webcam Resolution\",\"‎8 MP\"  ],\n  [\"Front Webcam Resolution\",\"‎5 MP\"  ],\n  [\"Hardware Platform\",\"‎Android\"  ],\n  [\"Operating System\",\"‎Android\"  ],\n  [\"Are Batteries Included\",\"‎Yes\"  ],\n  [\"Number Of Lithium Ion Cells\",\"‎1\"  ],\n  [\"Number of Lithium Metal Cells\",\"‎1\"  ],\n  [\"Included Components\",\"‎Travel adaptor, Data Cable, Ejection Pin, QSG.\"  ],\n  [\"Manufacturer\",\"‎Samsung\"  ],\n  [\"Country of Origin\",\"‎India\"  ],\n  [\"Item Weight\",\"‎508 g\"  ]\n]', 24999, 60, 28373, 'Tablet', '26.69cm (10.5 inch) & Vibrant Display & 1920x1200 & 16:10 & Android 11.0 & Quad speakers with Dolby & 8MP AF & 5.0MP Camera & 7040 mAh & 15W Fast Charging & 4 GB RAM & 64 GB ROM', 27999);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `productdb`
--
ALTER TABLE `productdb`
  ADD PRIMARY KEY (`Prod_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `productdb`
--
ALTER TABLE `productdb`
  MODIFY `Prod_id` int(128) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
